// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Shooting","status":true,"description":"マップ上での射撃を可能にします。","parameters":{"value":"2","r_value":"3","w_value":"4","s_value":"5","hp":"1","range":"10"}}
];
